const data = [
  {
    id: 1,
    category: "watch",
    img: "https://m.media-amazon.com/images/I/71XBcl6bNjL._AC_UL480_FMwebp_QL65_.jpg",
    name: "Watch SE",
    discription: "",
    price: "29,999",
    rating: "⭐⭐⭐⭐⭐",
  },
  {
    id: 2,
    category: "watch",
    img: "https://m.media-amazon.com/images/I/916acEhBkcL._AC_UL480_FMwebp_QL65_.jpg",
    name: "watch Ultra",
    discription: "",
    price: "82,900",
    rating: "⭐⭐⭐⭐⭐",
  },
  {
    id: 3,
    category: "watch",
    img: "https://m.media-amazon.com/images/I/7162zT9RKRL._AC_UL480_FMwebp_QL65_.jpg",
    name: " Watch series 9",
    discription: "",
    price: "44,900",
    rating: "⭐⭐⭐",
  },
  {
    id: 4,
    category: "watch",
    img: "https://m.media-amazon.com/images/I/71LfnkRgZ4L._AC_UL480_FMwebp_QL65_.jpg",
    name: "Watch SE(2nd Gen)",
    discription: "",
    price: "27,900",
    rating: "⭐⭐⭐⭐",
  },
  {
    id: 5,
    category: "watch",
    img: "https://m.media-amazon.com/images/I/61ulJeD5wVL._AC_UL480_FMwebp_QL65_.jpg",
    name: "Watch Series 6",
    discription: "",
    price: "35,999",
    rating: "⭐⭐⭐⭐",
  },
  {
    id: 6,
    category: "watch",
    img: "https://m.media-amazon.com/images/I/81w1BbNiwAL._AC_UL480_FMwebp_QL65_.jpg",
    name: "watch series 5",
    discription: "",
    price: "44,900",
    rating: "⭐⭐⭐⭐",
  },
  {
    id: 7,
    category: "watch",
    img: "https://m.media-amazon.com/images/I/71XkrRK2xAL._AC_UL480_FMwebp_QL65_.jpg",
    name: "Watch Series 4",
    discription: "",
    price: "32,000",
    rating: "⭐⭐⭐",
  },
  {
    id: 8,
    category: "watch",
    img: "https://m.media-amazon.com/images/I/81I70qV6cOL._AC_UL480_FMwebp_QL65_.jpg",
    name: "Watch Series 9",
    discription: "",
    price: "72,000",
    rating: "⭐⭐⭐⭐",
  },
  {
    id: 9,
    category: "watch",
    img: "https://m.media-amazon.com/images/I/713BLl3u37L._AC_UL480_FMwebp_QL65_.jpg",
    name: "Watch Series 3",
    discription: "",
    price: "24,000",
    rating: "⭐⭐⭐⭐⭐",
  },
  {
    id: 10,
    category: "watch",
    img: "https://m.media-amazon.com/images/I/81i9ZukGs+L._AC_UL480_FMwebp_QL65_.jpg",
    name: "Watch Ultra",
    discription: "",
    price: "89,900",
    rating: "⭐⭐⭐",
  },
  {
    id: 11,
    category: "iphone",
    img: "https://m.media-amazon.com/images/I/611mRs-imxL._AC_UY327_FMwebp_QL65_.jpg ",
    name: "iphone 6",
    discription: "",
    price: "50$",
    rating: "⭐⭐⭐⭐⭐",
  },
  {
    id: 12,
    category: "iphone",
    img: "https://m.media-amazon.com/images/I/71xb2xkN5qL._AC_UY327_FMwebp_QL65_.jpg ",
    name: "iphone 6",
    discription: "",
    price: "50$",
    rating: "⭐⭐⭐⭐",
  },
  {
    id: 13,
    category: "iphone",
    img: "https://m.media-amazon.com/images/I/71GLMJ7TQiL._AC_UY327_FMwebp_QL65_.jpg",
    name: "iphone 6",
    discription: "",
    price: "50$",
    rating: "⭐⭐⭐",
  },
  {
    id: 14,
    category: "iphone",
    img: "https://m.media-amazon.com/images/I/61VuVU94RnL._AC_UY327_FMwebp_QL65_.jpg ",
    name: "iphone 6",
    discription: "",
    price: "50$",
    rating: "⭐⭐",
  },
  {
    id: 15,
    category: "iphone",
    img: "https://m.media-amazon.com/images/I/71zFRCcMS2L._AC_UY327_FMwebp_QL65_.jpg ",
    name: "iphone 6",
    discription: "",
    price: "50$",
    rating: "⭐⭐⭐⭐",
  },
  {
    id: 16,
    category: "iphone",
    img: "https://m.media-amazon.com/images/I/61l9ppRIiqL._AC_UY327_FMwebp_QL65_.jpg",
    name: "iphone 6",
    discription: "",
    price: "50$",
    rating: "⭐⭐⭐",
  },
  {
    id: 17,
    category: "iphone",
    img: "https://m.media-amazon.com/images/I/81CgtwSII3L._AC_UY327_FMwebp_QL65_.jpg ",
    name: "iphone 6",
    discription: "",
    price: "50$",
    rating: "⭐⭐⭐⭐⭐",
  },
  {
    id: 18,
    category: "iphone",
    img: "https://m.media-amazon.com/images/I/71emcsxsRPL._AC_UY327_FMwebp_QL65_.jpg ",
    name: "iphone 6",
    discription: "",
    price: "50$",
    rating: "⭐⭐⭐",
  },
  {
    id: 19,
    category: "iphone",
    img: "https://m.media-amazon.com/images/I/71fVoqRC0wL._AC_UL480_FMwebp_QL65_.jpg ",
    name: "iphone 6",
    discription: "",
    price: "50$",
    rating: "⭐⭐⭐⭐",
  },
  {
    id: 20,
    category: "iphone",
    img: "https://m.media-amazon.com/images/I/51TpO+WrVpL._AC_UY327_FMwebp_QL65_.jpg ",
    name: "iphone 6",
    discription: "",
    price: "50$",
    rating: "⭐⭐⭐⭐",
  },
  {
    id: 21,
    category: "mac",
    img: "https://m.media-amazon.com/images/I/61YCWzjldDL._AC_UY327_FMwebp_QL65_.jpg",
    name: "2023 MacBook Pro ",
    discription:
      "14-inch, M3 chip with 8‑core CPU and 10‑core GPU, 8GB Unified Memory, 512GB - Space Grey",
    price: "1,69,900",
    rating: "⭐⭐⭐⭐⭐",
  },
  {
    id: 22,
    category: "mac",
    img: "https://m.media-amazon.com/images/I/61RJn0ofUsL._AC_UY327_FMwebp_QL65_.jpg",
    name: "2023 MacBook Pro ",
    discription:
      "14-inch, M3 Pro chip with 11‑core CPU and 14‑core GPU, 18GB Unified Memory, 512GB - Space Black",
    price: "1,99,900",
    rating: "⭐⭐⭐⭐⭐",
  },
  {
    id: 23,
    category: "mac",
    img: "https://m.media-amazon.com/images/I/71S4sIPFvBL._AC_UY327_FMwebp_QL65_.jpg ",
    name: "2023 MacBook Air",
    discription:
      "Air Laptop with M2 chip: 38.91 cm (15.3 inch) Liquid Retina Display, 8GB RAM 512GB SSD Storage",
    price: "1,54,900",
    rating: "⭐⭐⭐⭐",
  },
  {
    id: 24,
    category: "mac",
    img: "https://m.media-amazon.com/images/I/71f5Eu5lJSL._AC_UY327_FMwebp_QL65_.jpg ",
    name: "2022 MacBook Air",
    discription:
      "2022 MacBook Air Laptop with M2 chip: 34.46 cm (13.6-inch) Liquid Retina Display, 8GB RAM, 256GB SSD Storage",
    price: "1,14,900",
    rating: "⭐⭐⭐⭐⭐",
  },
  {
    id: 25,
    category: "mac",
    img: "https://m.media-amazon.com/images/I/618d5bS2lUL._AC_UY327_FMwebp_QL65_.jpg ",
    name: "2023 MacBook Pro",
    discription:
      "2023 MacBook Pro (16-inch, M3 Max chip with 16‑core CPU and 40‑core GPU, 48GB Unified Memory, 1TB)",
    price: "3,99,990",
    rating: "⭐⭐⭐⭐",
  },
  {
    id: 26,
    category: "mac",
    img: "https://rukminim2.flixcart.com/image/612/612/kp5sya80/screen-guard/tempered-glass/o/v/n/apple-macbook-air-m1-13-3-inch-lightwings-original-imag3gh5xftgbpg3.jpeg?q=70 ",
    name: "Apple 2020 Macbook",
    discription: "Apple 2020 Macbook Air Apple M1 - (8 GB/256 GB SSD)",
    price: "83,900",
    rating: "⭐⭐⭐⭐",
  },
  {
    id: 27,
    category: "mac",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/computer/r/a/f/macbook-air-thin-and-light-laptop-apple-original-imagqapzpa4vrajk.jpeg?q=70 ",
    name: "Apple 2023 Macbook",
    discription: "Apple 2023 Macbook Air Apple M2 - (8 GB/256 GB SSD)",
    price: "1,17,990",
    rating: "⭐⭐⭐⭐",
  },
  {
    id: 28,
    category: "mac",
    img: "https://rukminim2.flixcart.com/image/612/612/kp1imq80/allinone-desktop/u/m/3/mgtf3hn-a-apple-original-imag3d5thhhfgtyg.jpeg?q=70 ",
    name: "Apple 2021 iMac",
    discription: "Apple 2021 iMac with 4.5K Retina display M1",
    price: "1,30,990",
    rating: "⭐⭐⭐⭐⭐",
  },
  {
    id: 29,
    category: "mac",
    img: "https://rukminim2.flixcart.com/image/612/612/kuyf8nk0/computer/3/n/s/mk183hn-a-laptop-apple-original-imag7yzkbgbwvwq3.jpeg?q=70 ",
    name: "Apple 2021 Macbook Pro",
    discription: "Apple 2021 Macbook Pro Apple M1 Max - (32 GB/1 TB SSD)",
    price: "3,09,499",
    rating: "⭐⭐⭐⭐⭐",
  },
  {
    id: 30,
    category: "mac",
    img: "https://rukminim2.flixcart.com/image/612/612/xif0q/computer/k/s/m/-original-imagfdewfh9z3pee.jpeg?q=70 ",
    name: "Apple 2022 MacBook Pro",
    discription: "Apple 2022 MacBook Pro Apple M2 - (8 GB/256 GB SSD)",
    price: "1,09,990",
    rating: "⭐⭐⭐⭐⭐",
  },
  {
    id: 31,
    category: "ipad",
    img: "https://m.media-amazon.com/images/I/61uA2UVnYWL._AC_UY327_FMwebp_QL65_.jpg ",
    name: "iPad (10th Generation)",
    discription:
      "iPad (10th Generation): with A14 Bionic chip, 27.69 cm (10.9″) Liquid Retina Display, 64GB, Wi-Fi 6, 12MP front/12MP Back Camera",
    price: "39,990",
    rating: "⭐⭐⭐⭐",
  },
  {
    id: 32,
    category: "ipad",
    img: "https://m.media-amazon.com/images/I/61PnHlc0HCL._AC_UY327_FMwebp_QL65_.jpg",
    name: "iPad (9th Generation)",
    discription:
      "iPad (9th Generation): with A13 Bionic chip, 25.91 cm (10.2″) Retina Display, 64GB, Wi-Fi, 12MP front/8MP Back Camera",
    price: "32,900",
    rating: "⭐⭐⭐⭐",
  },
  {
    id: 33,
    category: "ipad",
    img: "https://m.media-amazon.com/images/I/61k05QwLuML._AC_UY327_FMwebp_QL65_.jpg",
    name: "iPad Air (5th Generation)",
    discription:
      "iPad Air (5th Generation): with M1 chip, 27.69 cm (10.9″) Liquid Retina Display, 64GB, Wi-Fi 6, 12MP front/12MP Back Camera",
    price: "58,299",
    rating: "⭐⭐⭐⭐",
  },
  {
    id: 34,
    category: "ipad",
    img: "https://m.media-amazon.com/images/I/61lv79X8rsL._AC_UY327_QL65_.jpg ",
    name: "Apple iPad Pro 11",
    discription:
      "Apple iPad Pro 11 (4th Generation): with M2 chip, Liquid Retina Display, 128GB, Wi-Fi 6E, 12MP front/12MP and 10MP Back Cameras",
    price: "79,990",
    rating: "⭐⭐⭐⭐⭐",
  },
  {
    id: 35,
    category: "ipad",
    img: "https://m.media-amazon.com/images/I/71o6PxcKkJL._AC_UY327_FMwebp_QL65_.jpg ",
    name: "iPad Mini (6th Generation)",
    discription:
      "iPad Mini (6th Generation): with A15 Bionic chip, 21.08 cm (8.3″) Liquid Retina Display, 64GB, Wi-Fi 6, 12MP front/12MP Back Camera",
    price: "48,399",
    rating: "⭐⭐⭐",
  },
  {
    id: 36,
    category: "ipad",
    img: "https://m.media-amazon.com/images/I/61hZrbHRMWL._AC_UY327_FMwebp_QL65_.jpg",
    name: "iPad Pro 11″ (4th Generation)",
    discription:
      "iPad Pro 11″ (4th Generation): with M2 chip, Liquid Retina Display, 256GB, Wi-Fi 6E + 5G Cellular, 12MP front/12MP and 10MP Back Cameras",
    price: "92,999",
    rating: "⭐⭐⭐",
  },
  {
    id: 37,
    category: "ipad",
    img: "https://m.media-amazon.com/images/I/71ey-9D8yDL._AC_UY327_FMwebp_QL65_.jpg ",
    name: "iPad Mini (6th Generation)",
    discription:
      "iPad Mini (6th Generation): with A15 Bionic chip, 21.08 cm (8.3″) Liquid Retina Display, 64GB, Wi-Fi 6, 12MP front/12MP Back Camera",
    price: "48,399",
    rating: "⭐⭐⭐⭐",
  },
  {
    id: 38,
    category: "ipad",
    img: "https://m.media-amazon.com/images/I/81hAx31maUL._AC_UY327_FMwebp_QL65_.jpg ",
    name: "iPad Pro 12.9″",
    discription:
      "iPad Pro 12.9″ (6th Generation): with M2 chip, Liquid Retina XDR Display, 128GB Wi-Fi 6E + 5G Cellular, 12MP front/12MP and 10MP Back Cameras",
    price: "1,24,990",
    rating: "⭐⭐⭐⭐⭐",
  },
  {
    id: 39,
    category: "ipad",
    img: "https://m.media-amazon.com/images/I/61NGnpjoRDL._AC_UY327_FMwebp_QL65_.jpg ",
    name: "iPad ",
    discription:
      "iPad (9th Generation): with A13 Bionic chip, 25.91 cm (10.2″) Retina Display, 256GB, Wi-Fi, 12MP front/8MP Back Camera",
    price: "45,900",
    rating: "⭐⭐⭐⭐",
  },
  {
    id: 40,
    category: "ipad",
    img: "https://m.media-amazon.com/images/I/61oo+mrbI2L._AC_UY327_FMwebp_QL65_.jpg ",
    name: "iPad Pro 12.9″",
    discription:
      "iPad Pro 12.9″ (6th Generation): with M2 chip, Liquid Retina XDR Display, 2TB, Wi-Fi 6E + 5G Cellular, 12MP front/12MP and 10MP Back Cameras",
    price: "2,09,990",
    rating: "⭐⭐⭐⭐",
  },
  {
    id: 41,
    category: "accessories",
    img: "https://m.media-amazon.com/images/I/41DxSSYn7oL._AC_UL480_FMwebp_QL65_.jpg ",
    name: "iPhone Charger 20W ",
    discription: "iPhone Charger Original 20W Adapter Fast USB Type C",
    price: "699",
    rating: "⭐⭐⭐⭐",
  },
  {
    id: 42,
    category: "accessories",
    img: "https://m.media-amazon.com/images/I/41Zfh4LxDiL._AC_UL480_FMwebp_QL65_.jpg ",
    name: "Headphone Jack Adapter",
    discription: "Lightning to 3.5 mm Headphone Jack Adapter",
    price: "999",
    rating: "⭐⭐⭐",
  },
  {
    id: 43,
    category: "accessories",
    img: "https://m.media-amazon.com/images/I/410eivKV4DL._AC_UL480_FMwebp_QL65_.jpg ",
    name: "EarPods with 3.5mm Headphone Plug",
    discription: "",
    price: "1699",
    rating: "⭐⭐⭐⭐⭐",
  },
  {
    id: 44,
    category: "accessories",
    img: "https://m.media-amazon.com/images/I/61OgxoLoreL._AC_UL480_FMwebp_QL65_.jpg ",
    name: "Apple iPhone Headphones Adapter",
    discription:
      "Apple iPhone Headphones Adapter, Lightning to 3.5mm Headphone",
    price: "249",
    rating: "⭐⭐⭐",
  },
  {
    id: 45,
    category: "accessories",
    img: "https://m.media-amazon.com/images/I/51pPPth9kyL._AC_UL480_FMwebp_QL65_.jpg ",
    name: "iPhone 15 Pro Clear Case with MagSafe ​​​​​​​",
    discription: "",
    price: "4,900",
    rating: "⭐⭐⭐⭐⭐",
  },
  {
    id: 46,
    category: "accessories",
    img: "https://m.media-amazon.com/images/I/71L5lSfJIPS._AC_UL480_FMwebp_QL65_.jpg ",
    name: "New Apple AirTag 4 Pack",
    discription: "",
    price: "11,900",
    rating: "⭐⭐⭐⭐⭐",
  },
  {
    id: 47,
    category: "accessories",
    img: "https://m.media-amazon.com/images/I/7120GgUKj3L._AC_UL480_FMwebp_QL65_.jpg ",
    name: "AirPods (2nd Generation) Case, White",
    discription: "",
    price: "11,990",
    rating: "⭐⭐⭐⭐⭐",
  },
  {
    id: 48,
    category: "accessories",
    img: "https://m.media-amazon.com/images/I/41tfqTRZdXL._AC_UL480_FMwebp_QL65_.jpg ",
    name: "USB-C to Lightning Cable -2m",
    discription: "",
    price: "2,900",
    rating: "⭐⭐⭐⭐",
  },
  {
    id: 49,
    category: "accessories",
    img: "https://m.media-amazon.com/images/I/51WwU0U5ImL._AC_UL480_FMwebp_QL65_.jpg ",
    name: "MAGTEC 500 23W 5 in 1 ",
    discription: "",
    price: "3,990",
    rating: "⭐⭐⭐⭐⭐",
  },
  {
    id: 50,
    category: "accessories",
    img: "https://m.media-amazon.com/images/I/419YQxJH6UL._AC_UL480_FMwebp_QL65_.jpg ",
    name: "Watch Magnetic Charging Cable (1 m)",
    discription: "",
    price: "2,900",
    rating: "⭐⭐⭐⭐",
  },
];

module.exports = data;
